define 'first_words', ->
  return [
    "Full",
    "Behavior",
    "Test",
    "User",
    "Requirement",
    "Extreme",
    "Lean",
    "Spiral",
    "Agile",
    "Rational",
    "Feature",
    "Reversible",
    "No-Retreat-No-Surrender",
    "Pair",
    "Small",
    "Big",
    "Collective",
    "Sustainable",
    "Decentralized",
    "Domain",
    "LSD",
    "Yoga",
    "Buzzword",
    "Intellectual",
    "Unified",
    "Convention",
    "Configuration",
    "Gender",
    "Sentient",
    "Minimum"
  ]

